#!/bin/sh
tr -d '<,>xyz=' < input \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f sim.awk \
	| awk -f energy.awk
